# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x05users\"1\n\x0b\x41uthRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1d\n\x0c\x41uthResponse\x12\r\n\x05token\x18\x01 \x01(\t\"\x1d\n\x0cTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"J\n\rTokenResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0b\n\x03sub\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\"8\n\x14\x44\x65stroyTokenResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xc4\x01\n\x0b\x41uthService\x12\x37\n\x0c\x41uthenticate\x12\x12.users.AuthRequest\x1a\x13.users.AuthResponse\x12:\n\rValidateToken\x12\x13.users.TokenRequest\x1a\x14.users.TokenResponse\x12@\n\x0c\x44\x65stroyToken\x12\x13.users.TokenRequest\x1a\x1b.users.DestroyTokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUTHREQUEST']._serialized_start=21
  _globals['_AUTHREQUEST']._serialized_end=70
  _globals['_AUTHRESPONSE']._serialized_start=72
  _globals['_AUTHRESPONSE']._serialized_end=101
  _globals['_TOKENREQUEST']._serialized_start=103
  _globals['_TOKENREQUEST']._serialized_end=132
  _globals['_TOKENRESPONSE']._serialized_start=134
  _globals['_TOKENRESPONSE']._serialized_end=208
  _globals['_DESTROYTOKENRESPONSE']._serialized_start=210
  _globals['_DESTROYTOKENRESPONSE']._serialized_end=266
  _globals['_AUTHSERVICE']._serialized_start=269
  _globals['_AUTHSERVICE']._serialized_end=465
# @@protoc_insertion_point(module_scope)
